### PR TITLE
Fix missing string quotes around json serialized enums (#146)

### LINKED ISSUE #146: Serializing enum values to json
When I serialize a class containing an enum value to json, it ends up with the enum name with no quotes, which results in an invalid json file. I'd like it to serialize as a string, how would I go about doing that? I've used [YamlMember(typeof(string))] on all my enum values for now, but would ideally like to be able to serialize all enum values to string, since adding this property is easily forgotten when adding new class members.

``` csharp
using YamlDotNet.Serialization;

public class Program
{
    public enum Primitive {Sphere, Cube}
    public Primitive type {get; set;}

    public static void Main()
    {
        var serializer = new Serializer(SerializationOptions.EmitDefaults | SerializationOptions.JsonCompatible);
        serializer.Serialize(System.Console.Out, new Program());
    }
}
```

The code above serializes to this:

``` json
{
  "type": Sphere
}
```

I would like it to serialize to this:

``` json
{
  "type": "Sphere"
}
```

### PR DESCRIPTION
**Pull request by KapuKapu**
Fixes #146 

Json allows only [String or Number](https://www.json.org/) as Enum serialization. I suggest serialization as String to enable cleaner handling in JS code and better readability.

### CODE REVIEW

File: YamlDotNet/Serialization/EventEmitters/JsonEventEmitter.cs [hunk 1]
```diff
@@ -53,9 +53,21 @@ public override void Emit(ScalarEventInfo eventInfo, IEmitter emitter)
...
+                        eventInfo.RenderedValue = YamlFormatter.FormatNumber(eventInfo.Source.Value);
+                    }
+                    break;
+
                 case TypeCode.Byte:
                 case TypeCode.Int16:
-                case TypeCode.Int32:
                 case TypeCode.Int64:
                 case TypeCode.SByte:
                 case TypeCode.UInt16:
```
Comment (am11) [inline YamlDotNet/Serialization/EventEmitters/JsonEventEmitter.cs]: Enums can be derived from any integer types. Perhaps, it could be something like https://github.com/am11/YamlDotNet/commit/d47770c3080518edccf50e48f8b0c0cc8fa97439?

File: YamlDotNet.Test/Serialization/SerializationTests.cs [hunk 2]
```diff
@@ -814,6 +814,17 @@ public void DeserializationOfDefaultsWorkInJson()
             result.MyString.Should().BeNull();
```
Comment (am11) [inline YamlDotNet.Test/Serialization/SerializationTests.cs]: Are the file mode changes (`100644->100755`) unintentional? To revert:

```sh
git update-index --chmod=-x YamlDotNet/Serialization/EventEmitters/JsonEventEmitter.cs YamlDotNet.Test/Serialization/SerializationTests.cs
```

File: YamlDotNet/Serialization/EventEmitters/JsonEventEmitter.cs (hunk 1 above)
Comment (KapuKapu) [reply YamlDotNet/Serialization/EventEmitters/JsonEventEmitter.cs]: Good catch, I will fix it.

File: YamlDotNet.Test/Serialization/SerializationTests.cs (hunk 2 above)
Comment (KapuKapu) [reply YamlDotNet.Test/Serialization/SerializationTests.cs]: Yes, it was unintentional.

File: YamlDotNet.Test/Serialization/SerializationTestHelper.cs [hunk 3]
```diff
@@ -141,6 +141,15 @@ public enum EnumExample
         Two
     }
 
+    public enum SByteEnum : sbyte { Default, Sbyte }
+    public enum ByteEnum : uint { Default, Byte }
```
Comment (am11) [inline YamlDotNet.Test/Serialization/SerializationTestHelper.cs]: This one was supposed to be `: byte` instead of `: uint`, my bad.

File: YamlDotNet/Serialization/EventEmitters/JsonEventEmitter.cs [hunk 4]
```diff
@@ -61,6 +61,18 @@ public override void Emit(ScalarEventInfo eventInfo, IEmitter emitter)
                 case TypeCode.UInt16:
                 case TypeCode.UInt32:
                 case TypeCode.UInt64:
+                    var valueIsEnum = eventInfo.Source.Value.GetType().IsEnum();
+                    if (valueIsEnum)
+                    {
+                        eventInfo.RenderedValue = eventInfo.Source.Value.ToString();
+                        eventInfo.Style = ScalarStyle.DoubleQuoted;
+                    }
+                    else
```
Comment (am11) [inline YamlDotNet/Serialization/EventEmitters/JsonEventEmitter.cs]: nit: `else` case can be removed so control will flow to common path (avoid repetition):

```c#
...
case TypeCode.UInt64:
    if (eventInfo.Source.Value.GetType().IsEnum)
    {
        eventInfo.RenderedValue = eventInfo.Source.Value.ToString();
        eventInfo.Style = ScalarStyle.DoubleQuoted;
        break;
    }

case TypeCode.Single:
...
```

File: YamlDotNet/Serialization/EventEmitters/JsonEventEmitter.cs [hunk 5]
```diff
@@ -61,6 +61,18 @@ public override void Emit(ScalarEventInfo eventInfo, IEmitter emitter)
                 case TypeCode.UInt16:
                 case TypeCode.UInt32:
                 case TypeCode.UInt64:
+                    var valueIsEnum = eventInfo.Source.Value.GetType().IsEnum();
```
Comment (aaubry) [inline YamlDotNet/Serialization/EventEmitters/JsonEventEmitter.cs]: I think that this should use `eventInfo.Source.Type` instead of `eventInfo.Source.Value.GetType()`. The `Type` property already contains the resolved type, so there's no need to retrieve it again.

File: YamlDotNet/Serialization/EventEmitters/JsonEventEmitter.cs (hunk 4 above)
Comment (KapuKapu) [reply YamlDotNet/Serialization/EventEmitters/JsonEventEmitter.cs]: This does not compile. All execution path of a case must contain a brake or none at all.

**Comment by aaubry** [comment]
Thanks!
