### PR TITLE
Fix issue #190

### LINKED ISSUE #190: OverridePropertyDescriptor doesn't lookup properties properly.
Currently, the `Deserializer` creates a type inspector like this.

    typeDescriptor.TypeDescriptor =
        new CachedTypeInspector(
            new YamlAttributesTypeInspector(
                new YamlAttributeOverridesInspector(
                    new NamingConventionTypeInspector(
                        new ReadableAndWritablePropertiesTypeInspector(
                            new ReadablePropertiesTypeInspector(
                                new StaticTypeResolver()
                            )
                        ),
                        namingConvention
                    ),
                    overrides
                )
            )
        );

Using a simple class like this:
```
public class Foo
{
	public bool IsRequired { get; set; }
}
```

And overrides:

```
var yao = new YamlAttributeOverrides();
var isRequiredAttribute = new YamlMemberAttribute();
isRequiredAttribute.Alias = "Required";
yao.Add(typeof(Foo), "IsRequired", isRequiredAttribute);
```

The `NamingConventionTypeInspector` returns an `IPropertyDescriptor` with the name **isRequired**.  Then the `YamlAttributeOverridesInspector` wraps this with an `OverridePropertyDescriptor`.  Later on in the serialization process `GetCustomAttribute` is called on the descriptor which checks the types (`Foo` in this case) for properties with the name `isRequired`.  This returns nothing because of the casing mismatch and as a result it skips the AttributeOverride lookup.  

So, that's the whole issue and I believe the solution is relatively simple.  Swapping the order of the `YamlAttributeOverridesInspector` and `NamingConventionTypeInspector` should be enough to resolve the issue.  I would assert that the `NamingConventionTypeInspector` should be placed after **both** the `YamlAttributesTypeInspector` and `YamlAttributeOverridesInspector` so that naming conventions are applied to overrides as well.

The `GetProperties` calls on the inspectors give this chain:

**YamlAttributeOverridesInspector (and lower):** IsRequired 
**YamlAttributesTypeInspector:** Required
**NamingConventionTypeInspector:** required 

Thoughts?

### PR DESCRIPTION
**Pull request by aaubry**
This fixes #190

### CODE REVIEW

File: YamlDotNet/Serialization/Deserializer.cs [hunk 1]
```diff
@@ -85,16 +85,16 @@ public IPropertyDescriptor GetProperty(Type type, object container, string name,
             typeDescriptor.TypeDescriptor =
                 new CachedTypeInspector(
                     new YamlAttributesTypeInspector(
-                        new YamlAttributeOverridesInspector(
-                            new NamingConventionTypeInspector(
+                        new NamingConventionTypeInspector(
```
Comment (veleek) [inline YamlDotNet/Serialization/Deserializer.cs]: Do you want to move NamingConventionTypeInspector outside of YamlAttributesTypeInspector as well?  With it inside the behavior is inconsistent.

If I have a property name FooBar with an attribute alias Foobar, and I use 'LowerCaseNamingConvention' then I believe the resulting output will be Foobar still (because it's applied after the naming convention).  But if you provide an AttributeOverride with the samething, the output will be foobar because the NamingConvention is applied after the attribute overrides.  I haven't validated this yet, but you can probably verify faster than I can.

File: YamlDotNet/Serialization/YamlAttributeOverridesInspector.cs [hunk 2]
```diff
@@ -93,18 +93,9 @@ public void Write(object target, object value)
...
-                if (prop != null)
-                {
-                    var attr = overrides.GetAttribute<T>(prop.DeclaringType, Name);
-                    if (attr != null)
-                        return attr;
-                }
-                
-                // Default to base behavior
-                return baseDescriptor.GetCustomAttribute<T>();
+            {
```
Comment (veleek) [inline YamlDotNet/Serialization/YamlAttributeOverridesInspector.cs]: Ahhh, MUCH cleaner. :)

File: YamlDotNet/Serialization/Deserializer.cs (hunk 1 above)
Comment (aaubry) [inline YamlDotNet/Serialization/Deserializer.cs]: I was also concerned about this, but this order works because the overrides does not change the name of the property, it adds a new attribute to the list, and then YamlAttributesTypeInspector will use the name from the attribute to override the naming convention.

File: YamlDotNet/Serialization/YamlAttributeOverridesInspector.cs (hunk 2 above)
Comment (aaubry) [inline YamlDotNet/Serialization/YamlAttributeOverridesInspector.cs]: Yes, I don't know why that code was reading the property again. It did not make sense to me.

File: YamlDotNet/Serialization/YamlAttributeOverrides.cs [hunk 3]
```diff
@@ -1,93 +1,182 @@
...
+            /// </summary>
+            /// <returns>The priority of the match. Higher values have more priority. Zero indicates no match.</returns>
+            public int Matches(Type matchType)
+            {
+                var currentPriority = 0;
+                var currentType = matchType;
+                while (currentType != null)
+                {
+                    ++currentPriority;
+                    if (currentType == matchType)
```
Comment (veleek) [inline YamlDotNet/Serialization/YamlAttributeOverrides.cs]: You're setting currentType to matchType at the top of this method so this matches immediately and caused it to return 1.

File: YamlDotNet/Serialization/YamlAttributeOverrides.cs [hunk 4]
```diff
@@ -1,93 +1,182 @@
...
+                    {
+                        return currentPriority;
+                    }
+                    currentType = currentType.BaseType;
+                }
+
+                if (matchType.GetInterfaces().Contains(matchType))
```
Comment (veleek) [inline YamlDotNet/Serialization/YamlAttributeOverrides.cs]: Is this what we want to do?  Should one of these be ReferenceType?

`ReferenceType.GetInterfaces().Contains(matchType)`?

File: YamlDotNet/Serialization/YamlAttributeOverrides.cs (hunk 3 above)
Comment (aaubry) [inline YamlDotNet/Serialization/YamlAttributeOverrides.cs]: Fixed. Thanks.

File: YamlDotNet/Serialization/YamlAttributeOverrides.cs (hunk 4 above)
Comment (aaubry) [inline YamlDotNet/Serialization/YamlAttributeOverrides.cs]: Fixed. Thanks.
