### PR TITLE
Fix Inf and NaN regex when using WithAttemptingUnquotedStringTypeDeserialization

### LINKED ISSUE #729: Strings with '.inf' in them being read as `Infinity`
**Describe the bug**
When using `WithAttemptingUnquotedStringTypeDeserialization`, strings with .inf in them are interpreted as `Float.Infinity`

**To Reproduce**
```
        // in DeserializerTests.cs
        [Theory]
        [InlineData("www.infinitetechnology.com", "www.infinitetechnology.com")]
        [InlineData("https://api.eastus-ms.inference.azureml.net", "https://api.eastus-ms.inference.azureml.net")]
        public void UnquotedStringTypeDeserializationHandlesInfinityAndNaNCorrectly(string yamlValue, string expected)
        {
            var deserializer = new DeserializerBuilder()
                .WithAttemptingUnquotedStringTypeDeserialization().Build();
            var yaml = $"Value: {yamlValue}";

            var resultVal = deserializer.Deserialize<Test>(yaml);
            Assert.Equal(expected, resultVal.Value); // works

            var resultDict = deserializer.Deserialize<IDictionary<string, object>>(yaml);
            Assert.True(resultDict.ContainsKey("Value"));
            Assert.Equal(expected, resultDict["Value"]);  // fails
        }
```

The bug is [here](https://github.com/aaubry/YamlDotNet/blob/6a7f2338468178d4061ad67b0493328bbbb92be6/YamlDotNet/Serialization/NodeDeserializers/ScalarNodeDeserializer.cs#L384).  The matching is unconstrained.

### PR DESCRIPTION
**Pull request by lkillgore**
Fixes #729.

Deserializing .INF and .NAN using WithAttemptingUnquotedStringTypeDeserialization

### CODE REVIEW

File: YamlDotNet/Serialization/NodeDeserializers/ScalarNodeDeserializer.cs [hunk 1]
```diff
@@ -381,7 +381,7 @@ private static object CastInteger(ulong number, TypeCode typeCode)
                             result = v;
                         }
                     }
-                    else if (Regex.IsMatch(v, @"[-+]?(\.inf|\.Inf|\.INF)")) //infinities
+                    else if (Regex.IsMatch(v, @"^[-+]?(\.inf|\.Inf|\.INF)$")) //infinities
```
Comment (jpricket) [inline YamlDotNet/Serialization/NodeDeserializers/ScalarNodeDeserializer.cs:384]: We don't allow for whitespace before or after, but I am guessing the string is trimmed long before it gets here.

**Comment by jpricket** [comment]
These changes make sense to me. One small comment.

**Review by jpricket — APPROVED** [review]

File: YamlDotNet/Serialization/NodeDeserializers/ScalarNodeDeserializer.cs (hunk 1 above)
Comment (lkillgore) [reply YamlDotNet/Serialization/NodeDeserializers/ScalarNodeDeserializer.cs:384]: In all my testing it's trimmed, but I don't know the code well enough to know if that's a guarantee.

**Review by stan-sz — APPROVED** [review]

**Comment by edwardcookemacu** [comment]
@jpricket  @lkillgore  The build failed so I can't merge this in. I'll try and look into it tonight. It may have been a fluke and just need to be requeued. When I get it merged in, I'll cut a new release.

**Comment by lkillgore** [comment]
Thanks, @edwardcookemacu!  I looked at the build failure, and it looks like it's the same one in this [PR](https://github.com/aaubry/YamlDotNet/pulls?q=is%3Apr+is%3Aclosed), which appears to be a transient failure AFAICT.

**Comment by aaubry** [comment]
This feature has been released in [version 12.0.2](https://github.com/aaubry/YamlDotNet/releases/tag/v12.0.2).
